"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
ratio = [1, 4, 3]
sort_by = "alphabetical"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
sort_translit = false
linemode = "none"
show_hidden = true
show_symlink = true
scrolloff = 5
mouse_events = ["click", "scroll"]
title_format = "Yazi: {cwd}"

[preview]
wrap = "no"
tab_size = 2
max_width = 600
max_height = 900
cache_dir = ""
image_delay = 30
image_filter = "triangle"
image_quality = 75
ueberzug_scale = 1
ueberzug_offset = [0, 0, 0, 0]

[opener]
edit = [
	{ run = '${EDITOR:-vi} %s', desc = "$EDITOR", block = true, for = "unix" },
	{ run = 'code %s', orphan = true, desc = "code", for = "windows" },
]
open = [
	{ run = 'xdg-open %s1', desc = "Open", for = "linux" },
	{ run = 'open %s', desc = "Open", for = "macos" },
	{ run = 'start "" %s1', desc = "Open", for = "windows", orphan = true },
]
reveal = [
	{ run = 'open -R %s1', desc = "Reveal", for = "macos" },
	{ run = 'xdg-open %d1', desc = "Reveal", for = "linux" },
	{ run = '''clear; exiftool %s1; echo "Press enter to exit"; read _''' }
]
extract = [
	{ run = 'ya pub extract --list %s', desc = "Extract here" },
]
tar_extract = [
	{ run = 'tar -xvf %s1', desc = "使用tar解压", block = true, for = "unix" },
]
rar_extract = [
	{ run = 'unar %s1', desc = "使用unar解压RAR", block = true, for = "unix" },
]

[open]
rules = [
	{ url = "*/", use = ["edit", "open", "reveal"] },
	{ mime = "text/*", use = ["edit", "reveal"] },
	{ mime = "image/*", use = ["open", "reveal"] },
	{ url = "*.tar", use = ["tar_extract", "reveal"] },
	{ url = "*.rar", use = ["rar_extract", "reveal"] },
	{ mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", use = ["extract", "reveal"] },
	{ url = "*", use = ["open", "reveal"] },
]

[tasks]
micro_workers = 10
macro_workers = 10
image_alloc = 536870912
image_bound = [10000, 10000]

[plugin]
fetchers = [
	{ id = "mime", url = "*/",          run = "mime.dir", prio = "high" },
	{ id = "mime", url = "local://*",   run = "mime.local", prio = "high" },
	{ id = "mime", url = "remote://*",  run = "mime.remote", prio = "high" },
]
spotters = [
	{ url = "*/", run = "folder" },
	{ mime = "text/*", run = "code" },
	{ mime = "image/*", run = "image" },
	{ url = "*", run = "file" },
]
previewers = [
	{ url = "*/", run = "folder" },
	{ mime = "text/*", run = "code" },
	{ mime = "application/json", run = "json" },
	{ mime = "image/*", run = "image" },
	{ mime = "application/pdf", run = "pdf" },
	{ mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive}", run = "archive" },
	{ url = "*", run = "file" },
]

[input]
cursor_blink = false

[confirm]
trash_title = "Trash {n} selected file{s}?"
delete_title = "Permanently delete {n} selected file{s}?"
overwrite_title = "Overwrite file?"
overwrite_body = "Will overwrite the following file:"
quit_title = "Quit?"
quit_body = "The following tasks are still running, are you sure you want to quit?"
